export const businessKeywords = [
    'Restaurants',
    'Hotels',
    'Cafes',
    'Coffee Shops',
    'Bars',
    'Nightclubs',
    'Bakeries',
    'Fast Food',
    'Pizza',
    'Gyms',
    'Fitness Centers',
    'Yoga Studios',
    'Spas',
    'Salons',
    'Barbershops',
    'Shopping Malls',
    'Grocery Stores',
    'Supermarkets',
    'Pharmacies',
    'Hospitals',
    'Clinics',
    'Dentists',
    'Banks',
    'ATMs',
    'Gas Stations',
    'Car Wash',
    'Auto Repair',
    'Mechanics',
    'Schools',
    'Universities',
    'Libraries',
    'Museums',
    'Parks',
    'Movie Theaters',
    'Cinemas',
    'Plumbers',
    'Electricians',
    'Carpenters',
    'Painters',
    'Contractors',
    'Real Estate',
    'Lawyers',
    'Accountants',
    'Consultants',
    'IT Services',
    'Pet Stores',
    'Veterinarians',
    'Florists',
    'Jewelry Stores',
    'Bookstores',
    'Clothing Stores',
    'Shoe Stores',
    'Electronics',
    'Furniture Stores',
    'Home Decor',
    'Hardware Stores',
    'Travel Agencies',
    'Insurance',
    'Dry Cleaners',
    'Laundromats',
];

export const locationSuggestions = [
    { city: 'New York', state: 'NY', country: 'USA', zipcode: '10001' },
    { city: 'Los Angeles', state: 'CA', country: 'USA', zipcode: '90001' },
    { city: 'Chicago', state: 'IL', country: 'USA', zipcode: '60601' },
    { city: 'Houston', state: 'TX', country: 'USA', zipcode: '77001' },
    { city: 'Phoenix', state: 'AZ', country: 'USA', zipcode: '85001' },
    { city: 'Philadelphia', state: 'PA', country: 'USA', zipcode: '19101' },
    { city: 'San Antonio', state: 'TX', country: 'USA', zipcode: '78201' },
    { city: 'San Diego', state: 'CA', country: 'USA', zipcode: '92101' },
    { city: 'Dallas', state: 'TX', country: 'USA', zipcode: '75201' },
    { city: 'San Jose', state: 'CA', country: 'USA', zipcode: '95101' },
    { city: 'London', state: 'England', country: 'UK', zipcode: 'SW1A 1AA' },
    { city: 'Paris', state: 'Île-de-France', country: 'France', zipcode: '75001' },
    { city: 'Tokyo', state: 'Kanto', country: 'Japan', zipcode: '100-0001' },
    { city: 'Dubai', state: 'Dubai', country: 'UAE', zipcode: '00000' },
    { city: 'Singapore', state: 'Singapore', country: 'Singapore', zipcode: '018956' },
    { city: 'Mumbai', state: 'Maharashtra', country: 'India', zipcode: '400001' },
    { city: 'Delhi', state: 'Delhi', country: 'India', zipcode: '110001' },
    { city: 'Bangalore', state: 'Karnataka', country: 'India', zipcode: '560001' },
    { city: 'Hyderabad', state: 'Telangana', country: 'India', zipcode: '500001' },
    { city: 'Chennai', state: 'Tamil Nadu', country: 'India', zipcode: '600001' },
    { city: 'Kolkata', state: 'West Bengal', country: 'India', zipcode: '700001' },
    { city: 'Pune', state: 'Maharashtra', country: 'India', zipcode: '411001' },
    { city: 'Ahmedabad', state: 'Gujarat', country: 'India', zipcode: '380001' },
    { city: 'Jaipur', state: 'Rajasthan', country: 'India', zipcode: '302001' },
    { city: 'Surat', state: 'Gujarat', country: 'India', zipcode: '395001' },
];
